### ISSUE TITLE
Hass.io installs armhf images on an armv7l system, causing add-ons not to work or update

### ISSUE THREAD

**Issue by ifol** [hassio-addons/addon-ubuntu-base#11]
An ESPHome image (1.12.2 -> 1.13.2) is not able to update with an error:

"This update is no longer compatible with your system."

After some investigation I've found out that the image no longer supports armhf architecure so Ive created an issue with ESPHome: https://github.com/esphome/issues/issues/371

There I was told that it's because this base addon stopped to support it and that my architecure detection might be wrong by Hass.io

That seems to be the case because my system is:

Linux orangepipc 4.19.38-sunxi #5.85 SMP ... armv7l armv7l armv7l GNU/Linux

And Home Assistant detects this correctly, from Info page:

arch 	armv7l
dev 	false
docker 	true
hassio 	true
os_name 	Linux
python_version 	3.7.3
version 	0.93.2
virtualenv 	false

However, Hass.io/docker installs armhf images instead of armv7 for some reason, breaking addons:

CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS               NAMES
59d4db90d27e        hassioaddons/node-red-armhf             "/init"                  2 hours ago         Up 2 hours                              addon_a0d7b954_nodered
baf8f2fe9826        esphome/esphome-hassio-armhf            "/init"                  2 hours ago         Up 2 hours                              addon_15ef4d2f_esphome
97d9ee16bc04        homeassistant/armhf-hassio-supervisor   "python3 -m hassio"      2 hours ago         Up 2 hours                              hassio_supervisor
8a6ba517f386        homeassistant/qemuarm-homeassistant     "/bin/entry.sh pytho…"   12 hours ago        Up 2 hours                              homeassistant

How can I force Hass.io to use the correct architecture? armv7 instead of armhf?

**Comment by ifol** [comment]
Maybe it's a problem of the script that I used to install hass.io?

https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh

There is a portion that says:

case $ARCH in
    "arm" | "armv7l" | "armv6l")
        if [ -z $MACHINE ]; then
            echo "[ERROR] Please set machine for $ARCH"
            exit 1
        fi
        HOMEASSISTANT_DOCKER="$DOCKER_REPO/$MACHINE-homeassistant"
        HASSIO_DOCKER="$DOCKER_REPO/armhf-hassio-supervisor"
    ;;

So it installs armhf-hassio-supervisor even when the arch is set to armv7l, could this cause the problem? Is there a way to migrate/switch to armv7l without losing my configuration and settings?

**Comment by frenck** [comment]
Not sure if that is the problem

Ubuntu (what this is based on) does not support armhf, only armv7.
It has never supported it. Since Hass.io now has support for armv7, the "artificial" armhf has been dropped.

I really think you should create an issue with Hass.io. From my end, there is nothing I can do. The images have the correct label, according to specifications.
